export const BIBLE_METADATA = [
  {
    id: '01',
    testamentum_la: 'Vetus Testamentum',
    testamentum_es: 'Antiguo Testamento',
    typus_la: 'Pentateuchus',
    typus_es: 'Pentateuco',
    acronymum_la: 'Gn',
    acronymum_es: 'Gn',
    nomen_la: 'Genesis',
    nomen_es: 'Génesis',
  },
  {
    id: '02',
    testamentum_la: 'Vetus Testamentum',
    testamentum_es: 'Antiguo Testamento',
    typus_la: 'Pentateuchus',
    typus_es: 'Pentateuco',
    acronymum_la: 'Ex',
    acronymum_es: 'Ex',
    nomen_la: 'Exodus',
    nomen_es: 'Éxodo',
  },
  {
    id: '03',
    testamentum_la: 'Vetus Testamentum',
    testamentum_es: 'Antiguo Testamento',
    typus_la: 'Pentateuchus',
    typus_es: 'Pentateuco',
    acronymum_la: 'Lv',
    acronymum_es: 'Lv',
    nomen_la: 'Leviticus',
    nomen_es: 'Levítico',
  },
  {
    id: '04',
    testamentum_la: 'Vetus Testamentum',
    testamentum_es: 'Antiguo Testamento',
    typus_la: 'Pentateuchus',
    typus_es: 'Pentateuco',
    acronymum_la: 'Nm',
    acronymum_es: 'Nm',
    nomen_la: 'Numeri',
    nomen_es: 'Números',
  },
  {
    id: '05',
    testamentum_la: 'Vetus Testamentum',
    testamentum_es: 'Antiguo Testamento',
    typus_la: 'Pentateuchus',
    typus_es: 'Pentateuco',
    acronymum_la: 'Dt',
    acronymum_es: 'Dt',
    nomen_la: 'Deuteronomium',
    nomen_es: 'Deuteronomio',
  },
  {
    id: '06',
    testamentum_la: 'Vetus Testamentum',
    testamentum_es: 'Antiguo Testamento',
    typus_la: 'Libri historici',
    typus_es: 'Libros históricos',
    acronymum_la: 'Ios',
    acronymum_es: 'Jos',
    nomen_la: 'Iosue',
    nomen_es: 'Josué',
  },
  {
    id: '07',
    testamentum_la: 'Vetus Testamentum',
    testamentum_es: 'Antiguo Testamento',
    typus_la: 'Libri historici',
    typus_es: 'Libros históricos',
    acronymum_la: 'Iud',
    acronymum_es: 'Jue',
    nomen_la: 'Iudices',
    nomen_es: 'Jueces',
  },
  {
    id: '08',
    testamentum_la: 'Vetus Testamentum',
    testamentum_es: 'Antiguo Testamento',
    typus_la: 'Libri historici',
    typus_es: 'Libros históricos',
    acronymum_la: 'Ruth',
    acronymum_es: 'Rut',
    nomen_la: 'Ruth',
    nomen_es: 'Rut',
  },
  {
    id: '09',
    testamentum_la: 'Vetus Testamentum',
    testamentum_es: 'Antiguo Testamento',
    typus_la: 'Libri historici',
    typus_es: 'Libros históricos',
    acronymum_la: '1 Reg',
    acronymum_es: '1 Sm',
    nomen_la: '1 Samuelis',
    nomen_es: '1 Samuel',
  },
  {
    id: '10',
    testamentum_la: 'Vetus Testamentum',
    testamentum_es: 'Antiguo Testamento',
    typus_la: 'Libri historici',
    typus_es: 'Libros históricos',
    acronymum_la: '2 Reg',
    acronymum_es: '2 Sm',
    nomen_la: '2 Samuelis',
    nomen_es: '2 Samuel',
  },
  {
    id: '11',
    testamentum_la: 'Vetus Testamentum',
    testamentum_es: 'Antiguo Testamento',
    typus_la: 'Libri historici',
    typus_es: 'Libros históricos',
    acronymum_la: '3 Reg',
    acronymum_es: '1 Re',
    nomen_la: '1 Regum',
    nomen_es: '1 Reyes',
  },
  {
    id: '12',
    testamentum_la: 'Vetus Testamentum',
    testamentum_es: 'Antiguo Testamento',
    typus_la: 'Libri historici',
    typus_es: 'Libros históricos',
    acronymum_la: '4 Reg',
    acronymum_es: '2 Re',
    nomen_la: '2 Regum',
    nomen_es: '2 Reyes',
  },
  {
    id: '13',
    testamentum_la: 'Vetus Testamentum',
    testamentum_es: 'Antiguo Testamento',
    typus_la: 'Libri historici',
    typus_es: 'Libros históricos',
    acronymum_la: '1 Par',
    acronymum_es: '1 Cr',
    nomen_la: '1 Paralipomenon',
    nomen_es: '1 Crónicas',
  },
  {
    id: '14',
    testamentum_la: 'Vetus Testamentum',
    testamentum_es: 'Antiguo Testamento',
    typus_la: 'Libri historici',
    typus_es: 'Libros históricos',
    acronymum_la: '2 Par',
    acronymum_es: '2 Cr',
    nomen_la: '2 Paralipomenon',
    nomen_es: '2 Crónicas',
  },
  {
    id: '15',
    testamentum_la: 'Vetus Testamentum',
    testamentum_es: 'Antiguo Testamento',
    typus_la: 'Libri historici',
    typus_es: 'Libros históricos',
    acronymum_la: 'Esd',
    acronymum_es: 'Esd',
    nomen_la: 'Esdras',
    nomen_es: 'Esdrás',
  },
  {
    id: '16',
    testamentum_la: 'Vetus Testamentum',
    testamentum_es: 'Antiguo Testamento',
    typus_la: 'Libri historici',
    typus_es: 'Libros históricos',
    acronymum_la: 'Neh',
    acronymum_es: 'Neh',
    nomen_la: 'Nehemias',
    nomen_es: 'Nehemías',
  },
  {
    id: '17',
    testamentum_la: 'Vetus Testamentum',
    testamentum_es: 'Antiguo Testamento',
    typus_la: 'Libri historici',
    typus_es: 'Libros históricos',
    acronymum_la: 'Tob',
    acronymum_es: 'Tob',
    nomen_la: 'Tobias',
    nomen_es: 'Tobías',
  },
  {
    id: '18',
    testamentum_la: 'Vetus Testamentum',
    testamentum_es: 'Antiguo Testamento',
    typus_la: 'Libri historici',
    typus_es: 'Libros históricos',
    acronymum_la: 'Iudt',
    acronymum_es: 'Jdt',
    nomen_la: 'Iudith',
    nomen_es: 'Judit',
  },
  {
    id: '19',
    testamentum_la: 'Vetus Testamentum',
    testamentum_es: 'Antiguo Testamento',
    typus_la: 'Libri historici',
    typus_es: 'Libros históricos',
    acronymum_la: 'Est',
    acronymum_es: 'Est',
    nomen_la: 'Esther',
    nomen_es: 'Ester',
  },
  {
    id: '20',
    testamentum_la: 'Vetus Testamentum',
    testamentum_es: 'Antiguo Testamento',
    typus_la: 'Libri historici',
    typus_es: 'Libros históricos',
    acronymum_la: '1 Mac',
    acronymum_es: '1 Mac',
    nomen_la: '1 Machabaeorum',
    nomen_es: '1 Macabeos',
  },
  {
    id: '21',
    testamentum_la: 'Vetus Testamentum',
    testamentum_es: 'Antiguo Testamento',
    typus_la: 'Libri historici',
    typus_es: 'Libros históricos',
    acronymum_la: '2 Mac',
    acronymum_es: '2 Mac',
    nomen_la: '2 Machabaeorum',
    nomen_es: '2 Macabeos',
  },
  {
    id: '22',
    testamentum_la: 'Vetus Testamentum',
    testamentum_es: 'Antiguo Testamento',
    typus_la: 'Libri sapientiales et poetici',
    typus_es: 'Libros sapienciales y poéticos',
    acronymum_la: 'Iob',
    acronymum_es: 'Job',
    nomen_la: 'Iob',
    nomen_es: 'Job',
  },
  {
    id: '23',
    testamentum_la: 'Vetus Testamentum',
    testamentum_es: 'Antiguo Testamento',
    typus_la: 'Libri sapientiales et poetici',
    typus_es: 'Libros sapienciales y poéticos',
    acronymum_la: 'Ps',
    acronymum_es: 'Sal',
    nomen_la: 'Psalmi',
    nomen_es: 'Salmos',
  },
  {
    id: '24',
    testamentum_la: 'Vetus Testamentum',
    testamentum_es: 'Antiguo Testamento',
    typus_la: 'Libri sapientiales et poetici',
    typus_es: 'Libros sapienciales y poéticos',
    acronymum_la: 'Prov',
    acronymum_es: 'Prov',
    nomen_la: 'Proverbia',
    nomen_es: 'Proverbios',
  },
  {
    id: '25',
    testamentum_la: 'Vetus Testamentum',
    testamentum_es: 'Antiguo Testamento',
    typus_la: 'Libri sapientiales et poetici',
    typus_es: 'Libros sapienciales y poéticos',
    acronymum_la: 'Qo',
    acronymum_es: 'Qo',
    nomen_la: 'Ecclesiastes',
    nomen_es: 'Eclesiastés',
  },
  {
    id: '26',
    testamentum_la: 'Vetus Testamentum',
    testamentum_es: 'Antiguo Testamento',
    typus_la: 'Libri sapientiales et poetici',
    typus_es: 'Libros sapienciales y poéticos',
    acronymum_la: 'Cant',
    acronymum_es: 'Ct',
    nomen_la: 'Canticum Canticorum',
    nomen_es: 'Cantar de los Cantares',
  },
  {
    id: '27',
    testamentum_la: 'Vetus Testamentum',
    testamentum_es: 'Antiguo Testamento',
    typus_la: 'Libri sapientiales et poetici',
    typus_es: 'Libros sapienciales y poéticos',
    acronymum_la: 'Sap',
    acronymum_es: 'Sab',
    nomen_la: 'Sapientia',
    nomen_es: 'Sabiduría',
  },
  {
    id: '28',
    testamentum_la: 'Vetus Testamentum',
    testamentum_es: 'Antiguo Testamento',
    typus_la: 'Libri sapientiales et poetici',
    typus_es: 'Libros sapienciales y poéticos',
    acronymum_la: 'Sir',
    acronymum_es: 'Eclo',
    nomen_la: 'Sirach',
    nomen_es: 'Eclesiástico',
  },
  {
    id: '29',
    testamentum_la: 'Vetus Testamentum',
    testamentum_es: 'Antiguo Testamento',
    typus_la: 'Libri prophetici',
    typus_es: 'Libros proféticos',
    acronymum_la: 'Is',
    acronymum_es: 'Is',
    nomen_la: 'Isaias',
    nomen_es: 'Isaías',
  },
  {
    id: '30',
    testamentum_la: 'Vetus Testamentum',
    testamentum_es: 'Antiguo Testamento',
    typus_la: 'Libri prophetici',
    typus_es: 'Libros proféticos',
    acronymum_la: 'Ier',
    acronymum_es: 'Jer',
    nomen_la: 'Ieremias',
    nomen_es: 'Jeremías',
  },
  {
    id: '31',
    testamentum_la: 'Vetus Testamentum',
    testamentum_es: 'Antiguo Testamento',
    typus_la: 'Libri prophetici',
    typus_es: 'Libros proféticos',
    acronymum_la: 'Lam',
    acronymum_es: 'Lam',
    nomen_la: 'Lamentationes',
    nomen_es: 'Lamentaciones',
  },
  {
    id: '32',
    testamentum_la: 'Vetus Testamentum',
    testamentum_es: 'Antiguo Testamento',
    typus_la: 'Libri prophetici',
    typus_es: 'Libros proféticos',
    acronymum_la: 'Bar',
    acronymum_es: 'Bar',
    nomen_la: 'Baruch',
    nomen_es: 'Baruc',
  },
  {
    id: '33',
    testamentum_la: 'Vetus Testamentum',
    testamentum_es: 'Antiguo Testamento',
    typus_la: 'Libri prophetici',
    typus_es: 'Libros proféticos',
    acronymum_la: 'Ez',
    acronymum_es: 'Ez',
    nomen_la: 'Ezechiel',
    nomen_es: 'Ezequiel',
  },
  {
    id: '34',
    testamentum_la: 'Vetus Testamentum',
    testamentum_es: 'Antiguo Testamento',
    typus_la: 'Libri prophetici',
    typus_es: 'Libros proféticos',
    acronymum_la: 'Dan',
    acronymum_es: 'Dan',
    nomen_la: 'Daniel',
    nomen_es: 'Daniel',
  },
  {
    id: '35',
    testamentum_la: 'Vetus Testamentum',
    testamentum_es: 'Antiguo Testamento',
    typus_la: 'Libri prophetici',
    typus_es: 'Libros proféticos',
    acronymum_la: 'Os',
    acronymum_es: 'Os',
    nomen_la: 'Osee',
    nomen_es: 'Oseas',
  },
  {
    id: '36',
    testamentum_la: 'Vetus Testamentum',
    testamentum_es: 'Antiguo Testamento',
    typus_la: 'Libri prophetici',
    typus_es: 'Libros proféticos',
    acronymum_la: 'Ioel',
    acronymum_es: 'Jl',
    nomen_la: 'Ioel',
    nomen_es: 'Joel',
  },
  {
    id: '37',
    testamentum_la: 'Vetus Testamentum',
    testamentum_es: 'Antiguo Testamento',
    typus_la: 'Libri prophetici',
    typus_es: 'Libros proféticos',
    acronymum_la: 'Am',
    acronymum_es: 'Am',
    nomen_la: 'Amos',
    nomen_es: 'Amós',
  },
  {
    id: '38',
    testamentum_la: 'Vetus Testamentum',
    testamentum_es: 'Antiguo Testamento',
    typus_la: 'Libri prophetici',
    typus_es: 'Libros proféticos',
    acronymum_la: 'Abd',
    acronymum_es: 'Abd',
    nomen_la: 'Abdias',
    nomen_es: 'Abdías',
  },
  {
    id: '39',
    testamentum_la: 'Vetus Testamentum',
    testamentum_es: 'Antiguo Testamento',
    typus_la: 'Libri prophetici',
    typus_es: 'Libros proféticos',
    acronymum_la: 'Ion',
    acronymum_es: 'Jon',
    nomen_la: 'Ionas',
    nomen_es: 'Jonás',
  },
  {
    id: '40',
    testamentum_la: 'Vetus Testamentum',
    testamentum_es: 'Antiguo Testamento',
    typus_la: 'Libri prophetici',
    typus_es: 'Libros proféticos',
    acronymum_la: 'Mich',
    acronymum_es: 'Miq',
    nomen_la: 'Michaeas',
    nomen_es: 'Miqueas',
  },
  {
    id: '41',
    testamentum_la: 'Vetus Testamentum',
    testamentum_es: 'Antiguo Testamento',
    typus_la: 'Libri prophetici',
    typus_es: 'Libros proféticos',
    acronymum_la: 'Nah',
    acronymum_es: 'Nah',
    nomen_la: 'Nahum',
    nomen_es: 'Nahún',
  },
  {
    id: '42',
    testamentum_la: 'Vetus Testamentum',
    testamentum_es: 'Antiguo Testamento',
    typus_la: 'Libri prophetici',
    typus_es: 'Libros proféticos',
    acronymum_la: 'Hab',
    acronymum_es: 'Hab',
    nomen_la: 'Habacuc',
    nomen_es: 'Habacuc',
  },
  {
    id: '43',
    testamentum_la: 'Vetus Testamentum',
    testamentum_es: 'Antiguo Testamento',
    typus_la: 'Libri prophetici',
    typus_es: 'Libros proféticos',
    acronymum_la: 'Soph',
    acronymum_es: 'Sof',
    nomen_la: 'Sophonias',
    nomen_es: 'Sofonías',
  },
  {
    id: '44',
    testamentum_la: 'Vetus Testamentum',
    testamentum_es: 'Antiguo Testamento',
    typus_la: 'Libri prophetici',
    typus_es: 'Libros proféticos',
    acronymum_la: 'Agg',
    acronymum_es: 'Ag',
    nomen_la: 'Aggaeus',
    nomen_es: 'Ageo',
  },
  {
    id: '45',
    testamentum_la: 'Vetus Testamentum',
    testamentum_es: 'Antiguo Testamento',
    typus_la: 'Libri prophetici',
    typus_es: 'Libros proféticos',
    acronymum_la: 'Zach',
    acronymum_es: 'Zac',
    nomen_la: 'Zacharias',
    nomen_es: 'Zacarías',
  },
  {
    id: '46',
    testamentum_la: 'Vetus Testamentum',
    testamentum_es: 'Antiguo Testamento',
    typus_la: 'Libri prophetici',
    typus_es: 'Libros proféticos',
    acronymum_la: 'Mal',
    acronymum_es: 'Mal',
    nomen_la: 'Malachias',
    nomen_es: 'Malaquías',
  },
  {
    id: '47',
    testamentum_la: 'Novum Testamentum',
    testamentum_es: 'Nuevo Testamento',
    typus_la: 'Evangelia',
    typus_es: 'Evangelios',
    acronymum_la: 'Mt',
    acronymum_es: 'Mt',
    nomen_la: 'Matthaeus',
    nomen_es: 'Mateo',
  },
  {
    id: '48',
    testamentum_la: 'Novum Testamentum',
    testamentum_es: 'Nuevo Testamento',
    typus_la: 'Evangelia',
    typus_es: 'Evangelios',
    acronymum_la: 'Mc',
    acronymum_es: 'Mc',
    nomen_la: 'Marcus',
    nomen_es: 'Marcos',
  },
  {
    id: '49',
    testamentum_la: 'Novum Testamentum',
    testamentum_es: 'Nuevo Testamento',
    typus_la: 'Evangelia',
    typus_es: 'Evangelios',
    acronymum_la: 'Lc',
    acronymum_es: 'Lc',
    nomen_la: 'Lucas',
    nomen_es: 'Lucas',
  },
  {
    id: '50',
    testamentum_la: 'Novum Testamentum',
    testamentum_es: 'Nuevo Testamento',
    typus_la: 'Evangelia',
    typus_es: 'Evangelios',
    acronymum_la: 'Io',
    acronymum_es: 'Jn',
    nomen_la: 'Ioannes',
    nomen_es: 'Juan',
  },
  {
    id: '51',
    testamentum_la: 'Novum Testamentum',
    testamentum_es: 'Nuevo Testamento',
    typus_la: 'Actus Apostolorum',
    typus_es: 'Hechos de los apóstoles',
    acronymum_la: 'Act',
    acronymum_es: 'Hch',
    nomen_la: 'Actus Apostolorum',
    nomen_es: 'Hechos de los apóstoles',
  },
  {
    id: '52',
    testamentum_la: 'Novum Testamentum',
    testamentum_es: 'Nuevo Testamento',
    typus_la: 'Corpus paulinum',
    typus_es: 'Corpus paulino',
    acronymum_la: 'Rom',
    acronymum_es: 'Rom',
    nomen_la: 'Epistula ad Romanos',
    nomen_es: 'Romanos',
  },
  {
    id: '53',
    testamentum_la: 'Novum Testamentum',
    testamentum_es: 'Nuevo Testamento',
    typus_la: 'Corpus paulinum',
    typus_es: 'Corpus paulino',
    acronymum_la: '1 Cor',
    acronymum_es: '1 Co',
    nomen_la: '1 ad Corinthios',
    nomen_es: '1 Corintios',
  },
  {
    id: '54',
    testamentum_la: 'Novum Testamentum',
    testamentum_es: 'Nuevo Testamento',
    typus_la: 'Corpus paulinum',
    typus_es: 'Corpus paulino',
    acronymum_la: '2 Cor',
    acronymum_es: '2 Co',
    nomen_la: '2 ad Corinthios',
    nomen_es: '2 Corintios',
  },
  {
    id: '55',
    testamentum_la: 'Novum Testamentum',
    testamentum_es: 'Nuevo Testamento',
    typus_la: 'Corpus paulinum',
    typus_es: 'Corpus paulino',
    acronymum_la: 'Gal',
    acronymum_es: 'Gal',
    nomen_la: 'ad Galatas',
    nomen_es: 'Gálatas',
  },
  {
    id: '56',
    testamentum_la: 'Novum Testamentum',
    testamentum_es: 'Nuevo Testamento',
    typus_la: 'Corpus paulinum',
    typus_es: 'Corpus paulino',
    acronymum_la: 'Eph',
    acronymum_es: 'Ef',
    nomen_la: 'ad Ephesios',
    nomen_es: 'Efesios',
  },
  {
    id: '57',
    testamentum_la: 'Novum Testamentum',
    testamentum_es: 'Nuevo Testamento',
    typus_la: 'Corpus paulinum',
    typus_es: 'Corpus paulino',
    acronymum_la: 'Phil',
    acronymum_es: 'Flp',
    nomen_la: 'ad Philippenses',
    nomen_es: 'Filipenses',
  },
  {
    id: '58',
    testamentum_la: 'Novum Testamentum',
    testamentum_es: 'Nuevo Testamento',
    typus_la: 'Corpus paulinum',
    typus_es: 'Corpus paulino',
    acronymum_la: 'Col',
    acronymum_es: 'Col',
    nomen_la: 'ad Colossenses',
    nomen_es: 'Colosenses',
  },
  {
    id: '59',
    testamentum_la: 'Novum Testamentum',
    testamentum_es: 'Nuevo Testamento',
    typus_la: 'Corpus paulinum',
    typus_es: 'Corpus paulino',
    acronymum_la: '1 Thess',
    acronymum_es: '1 Tes',
    nomen_la: '1 ad Thessalonicenses',
    nomen_es: '1 Tesalonicenses',
  },
  {
    id: '60',
    testamentum_la: 'Novum Testamentum',
    testamentum_es: 'Nuevo Testamento',
    typus_la: 'Corpus paulinum',
    typus_es: 'Corpus paulino',
    acronymum_la: '2 Thess',
    acronymum_es: '2 Tes',
    nomen_la: '2 ad Thessalonicenses',
    nomen_es: '2 Tesalonicenses',
  },
  {
    id: '61',
    testamentum_la: 'Novum Testamentum',
    testamentum_es: 'Nuevo Testamento',
    typus_la: 'Corpus paulinum',
    typus_es: 'Corpus paulino',
    acronymum_la: '1 Tim',
    acronymum_es: '1 Tim',
    nomen_la: '1 ad Timotheum',
    nomen_es: '1 Timoteo',
  },
  {
    id: '62',
    testamentum_la: 'Novum Testamentum',
    testamentum_es: 'Nuevo Testamento',
    typus_la: 'Corpus paulinum',
    typus_es: 'Corpus paulino',
    acronymum_la: '2 Tim',
    acronymum_es: '2 Tim',
    nomen_la: '2 ad Timotheum',
    nomen_es: '2 Timoteo',
  },
  {
    id: '63',
    testamentum_la: 'Novum Testamentum',
    testamentum_es: 'Nuevo Testamento',
    typus_la: 'Corpus paulinum',
    typus_es: 'Corpus paulino',
    acronymum_la: 'Tit',
    acronymum_es: 'Tit',
    nomen_la: 'ad Titum',
    nomen_es: 'Tito',
  },
  {
    id: '64',
    testamentum_la: 'Novum Testamentum',
    testamentum_es: 'Nuevo Testamento',
    typus_la: 'Corpus paulinum',
    typus_es: 'Corpus paulino',
    acronymum_la: 'Phlm',
    acronymum_es: 'Flm',
    nomen_la: 'ad Philemonem',
    nomen_es: 'Filemón',
  },
  {
    id: '65',
    testamentum_la: 'Novum Testamentum',
    testamentum_es: 'Nuevo Testamento',
    typus_la: 'Corpus paulinum',
    typus_es: 'Corpus paulino',
    acronymum_la: 'Heb',
    acronymum_es: 'Heb',
    nomen_la: 'ad Hebraeos',
    nomen_es: 'Hebreos',
  },
  {
    id: '66',
    testamentum_la: 'Novum Testamentum',
    testamentum_es: 'Nuevo Testamento',
    typus_la: 'Epistulae catholicae',
    typus_es: 'Cartas católicas',
    acronymum_la: 'Iac',
    acronymum_es: 'Stg',
    nomen_la: 'Iacobi',
    nomen_es: 'Santiago',
  },
  {
    id: '67',
    testamentum_la: 'Novum Testamentum',
    testamentum_es: 'Nuevo Testamento',
    typus_la: 'Epistulae catholicae',
    typus_es: 'Cartas católicas',
    acronymum_la: '1 Ptr',
    acronymum_es: '1 Pe',
    nomen_la: '1 Petri',
    nomen_es: '1 Pedro',
  },
  {
    id: '68',
    testamentum_la: 'Novum Testamentum',
    testamentum_es: 'Nuevo Testamento',
    typus_la: 'Epistulae catholicae',
    typus_es: 'Cartas católicas',
    acronymum_la: '2 Ptr',
    acronymum_es: '2 Pe',
    nomen_la: '2 Petri',
    nomen_es: '2 Pedro',
  },
  {
    id: '69',
    testamentum_la: 'Novum Testamentum',
    testamentum_es: 'Nuevo Testamento',
    typus_la: 'Epistulae Ioannis',
    typus_es: 'Cartas de San Juan',
    acronymum_la: '1 Io',
    acronymum_es: '1 Jn',
    nomen_la: '1 Ioannis',
    nomen_es: '1 Juan',
  },
  {
    id: '70',
    testamentum_la: 'Novum Testamentum',
    testamentum_es: 'Nuevo Testamento',
    typus_la: 'Epistulae Ioannis',
    typus_es: 'Cartas de San Juan',
    acronymum_la: '2 Io',
    acronymum_es: '2 Jn',
    nomen_la: '2 Ioannis',
    nomen_es: '2 Juan',
  },
  {
    id: '71',
    testamentum_la: 'Novum Testamentum',
    testamentum_es: 'Nuevo Testamento',
    typus_la: 'Epistulae Ioannis',
    typus_es: 'Cartas de San Juan',
    acronymum_la: '3 Io',
    acronymum_es: '3 Jn',
    nomen_la: '3 Ioannis',
    nomen_es: '3 Juan',
  },
  {
    id: '72',
    testamentum_la: 'Novum Testamentum',
    testamentum_es: 'Nuevo Testamento',
    typus_la: 'Iudas',
    typus_es: 'Judas',
    acronymum_la: 'Iud',
    acronymum_es: 'Jud',
    nomen_la: 'Iudae',
    nomen_es: 'Judas',
  },
  {
    id: '73',
    testamentum_la: 'Novum Testamentum',
    testamentum_es: 'Nuevo Testamento',
    typus_la: 'Apocalypsis',
    typus_es: 'Apocalipsis',
    acronymum_la: 'Ap',
    acronymum_es: 'Ap',
    nomen_la: 'Apocalypsis',
    nomen_es: 'Apocalipsis',
  },
];
